# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "vk-ruby"
  s.version = "0.7.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andrew Zinenko"]
  s.date = "2011-11-23"
  s.description = " Ruby wrapper for vk.com API "
  s.email = "zinenkoan@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/vk-ruby.rb",
    "lib/vk-ruby/api/base.yml",
    "lib/vk-ruby/api/ext.yml",
    "lib/vk-ruby/api/secure.yml",
    "lib/vk-ruby/core.rb",
    "lib/vk-ruby/secure.rb",
    "lib/vk-ruby/serverside.rb",
    "lib/vk-ruby/standalone.rb",
    "lib/vk-ruby/vk_exception.rb",
    "tests/helpers.rb",
    "tests/secure_test.rb",
    "tests/serverside_test.rb",
    "tests/standalone_test.rb",
    "vk-ruby.gemspec"
  ]
  s.homepage = "http://github.com/zinenko/vk-ruby"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Ruby wrapper for vk.com API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<transformer>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<minitest>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<json>, [">= 0"])
      s.add_development_dependency(%q<json-jruby>, [">= 0"])
      s.add_development_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_runtime_dependency(%q<transformer>, [">= 0"])
    else
      s.add_dependency(%q<transformer>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
      s.add_dependency(%q<json-jruby>, [">= 0"])
      s.add_dependency(%q<jruby-openssl>, [">= 0"])
      s.add_dependency(%q<transformer>, [">= 0"])
    end
  else
    s.add_dependency(%q<transformer>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
    s.add_dependency(%q<json-jruby>, [">= 0"])
    s.add_dependency(%q<jruby-openssl>, [">= 0"])
    s.add_dependency(%q<transformer>, [">= 0"])
  end
end

